### ISSUE TITLE
Write each action(option) as a function

### ISSUE THREAD

**Issue by kiwirives** [MASACR99/Image_Comparator#6]
I guess you don't give a sh*t, but it would be prettier to have separate functions for each action(option)

For example:
https://github.com/MASACR99/Image_Comparator/blob/0fe118de1d7de7ed382b78a70dae7c3c0ff40390/CompareImage.cpp#L92-L111

Could be:
```cpp
 ...
 case 1: 
 	deleteSmallerDuplicate();
 	break; 
 case 2: 
 ...
```

PS: it's *smaller* not *lower* :P

**Comment by MASACR99** [comment]
solved in next update!
